import {
  GiWheat,
  GiCorn,
  GiPlantSeed,
  GiFarmer,
  GiDroplet,
  GiHerbsBundle,
  GiCottonFlower,
  GiGarlic,
  GiChickpeas,
  GiPeanut,
  GiOnion,
  GiPeas,
  GiPotato,
  GiFlowerEmblem,
  GiRice,
  GiSesame,
  GiSugarCane,
  GiSunflower,
  GiTurmeric,
  GiGrass,
  GiLentils,
  GiPlantRoots,
  GiBeanstalk,
  GiGingerRoot,
  GiBean,
} from "../icons/Cropicons";
// Crop data with seasons, types, and detailed descriptions
const cropData = [
  {
    name: "Arhar/Tur",
    season: "Kharif",
    type: "Pulses",
    icon: <GiPlantSeed className="text-amber-600" />,
    description: "Pigeon pea, drought-resistant pulse crop",
    idealConditions: "Well-drained soil, 25-35°C temperature",
  },
  {
    name: "Bajra",
    season: "Kharif",
    type: "Cereals",
    icon: <GiWheat className="text-yellow-500" />,
    description: "Pearl millet, heat and drought tolerant",
    idealConditions: "Sandy soils, 25-30°C temperature",
  },
  {
    name: "Barley",
    season: "Rabi",
    type: "Cereals",
    icon: <GiWheat className="text-yellow-700" />,
    description: "Cool-season cereal crop",
    idealConditions: "Cool, dry climate, loamy soil",
  },
  {
    name: "Castor Seed",
    season: "Kharif",
    type: "Oilseeds",
    icon: <GiDroplet className="text-purple-600" />,
    description: "Oilseed crop used for castor oil",
    idealConditions: "Well-drained sandy loam, warm climate",
  },
  {
    name: "Coriander",
    season: "Whole year",
    type: "Spices",
    icon: <GiHerbsBundle className="text-green-500" />,
    description: "Aromatic herb and spice crop",
    idealConditions: "Cool and dry weather, loamy soil",
  },
  {
    name: "Cotton(Lint)",
    season: "Kharif",
    type: "Fiber Crops",
    icon: <GiCottonFlower className="text-gray-400" />,
    description: "Fiber crop used in textile industry",
    idealConditions: "Black soil, 25-35°C, moderate rainfall",
  },
  {
    name: "Garlic",
    season: "Whole year",
    type: "Spices",
    icon: <GiGarlic className="text-white" />,
    description: "Pungent spice with medicinal value",
    idealConditions: "Cool climate, well-drained soil",
  },
  {
    name: "Ginger",
    season: "Whole year",
    type: "Spices",
    icon: <GiGingerRoot className="text-orange-700" />,
    description: "Rhizome crop used as spice and medicine",
    idealConditions: "Warm, humid climate, loamy soil",
  },
  {
    name: "Gram",
    season: "Rabi",
    type: "Pulses",
    icon: <GiChickpeas className="text-yellow-800" />,
    description: "Chickpea, important Rabi pulse",
    idealConditions: "Cool climate, well-drained soil",
  },
  {
    name: "Groundnut",
    season: "Kharif",
    type: "Oilseeds",
    icon: <GiPeanut className="text-brown-600" />,
    description: "Major oilseed crop, nitrogen-fixing",
    idealConditions: "Well-drained sandy loam, warm climate",
  },
  {
    name: "Horse-Gram",
    season: "Kharif",
    type: "Pulses",
    icon: <GiBean className="text-red-700" />,
    description: "Drought-resistant legume",
    idealConditions: "Poor soils, dry conditions",
  },
  {
    name: "Jowar",
    season: "Kharif",
    type: "Cereals",
    icon: <GiCorn className="text-yellow-600" />,
    description: "Sorghum, drought-tolerant cereal",
    idealConditions: "Sandy loam soil, warm and dry climate",
  },
  {
    name: "Maize",
    season: "Kharif",
    type: "Cereals",
    icon: <GiCorn className="text-yellow-500" />,
    description: "Widely cultivated cereal crop",
    idealConditions: "Warm weather, loamy soil",
  },
  {
    name: "Masoor",
    season: "Rabi",
    type: "Pulses",
    icon: <GiLentils className="text-orange-500" />,
    description: "Lentil, winter season pulse",
    idealConditions: "Cool climate, well-drained soil",
  },
  {
    name: "Moong(Green Gram)",
    season: "Kharif",
    type: "Pulses",
    icon: <GiBean className="text-green-600" />,
    description: "Short-duration legume crop",
    idealConditions: "Loamy soil, warm and humid weather",
  },
  {
    name: "Moth",
    season: "Kharif",
    type: "Pulses",
    icon: <GiBean className="text-brown-500" />,
    description: "Legume crop for arid regions",
    idealConditions: "Poor soils, dry and hot conditions",
  },
  {
    name: "Onion",
    season: "Whole year",
    type: "Vegetable",
    icon: <GiOnion className="text-red-500" />,
    description: "Bulb crop, staple in cuisine",
    idealConditions: "Cool season, fertile sandy loam",
  },
  {
    name: "Other Oilseeds",
    season: "Rabi",
    type: "Oilseeds",
    icon: <GiDroplet className="text-yellow-700" />,
    description: "Various oilseed crops",
    idealConditions: "Depends on crop, generally well-drained soil",
  },
  {
    name: "Peas & Beans (Pulses)",
    season: "Kharif",
    type: "Pulses",
    icon: <GiPeas className="text-green-600" />,
    description: "Leguminous food crops",
    idealConditions: "Cool to moderate climate",
  },
  {
    name: "Peas & Beans (Pulses)",
    season: "Rabi",
    type: "Pulses",
    icon: <GiPeas className="text-green-400" />,
    description: "Leguminous food crops",
    idealConditions: "Cool season, fertile soil",
  },
  {
    name: "Potato",
    season: "Whole year",
    type: "Vegetable",
    icon: <GiPotato className="text-yellow-800" />,
    description: "Tuber crop, rich in carbohydrates",
    idealConditions: "Cool climate, well-drained loamy soil",
  },
  {
    name: "Rapeseed & Mustard",
    season: "Rabi",
    type: "Oilseeds",
    icon: <GiFlowerEmblem className="text-yellow-600" />,
    description: "Oilseed crops grown in winter",
    idealConditions: "Cool season, well-drained soil",
  },
  {
    name: "Rice",
    season: "Kharif",
    type: "Cereals",
    icon: <GiRice className="text-green-700" />,
    description: "Staple food grain, water-loving",
    idealConditions: "High rainfall, clayey soil",
  },
  {
    name: "Sesamum",
    season: "Kharif",
    type: "Oilseeds",
    icon: <GiSesame className="text-gray-700" />,
    description: "Oilseed crop rich in nutrients",
    idealConditions: "Warm climate, light soil",
  },
  {
    name: "Sugarcane",
    season: "Whole year",
    type: "Sugar",
    icon: <GiSugarCane className="text-green-500" />,
    description: "Tall perennial grass used for sugar",
    idealConditions: "Tropical climate, rich loam",
  },
  {
    name: "Sunflower",
    season: "Kharif",
    type: "Oilseeds",
    icon: <GiSunflower className="text-yellow-500" />,
    description: "Oilseed with attractive yellow flower",
    idealConditions: "Loamy soil, warm climate",
  },
  {
    name: "Turmeric",
    season: "Whole year",
    type: "Spices",
    icon: <GiTurmeric className="text-orange-600" />,
    description: "Rhizome spice with medicinal value",
    idealConditions: "Hot, humid climate, well-drained soil",
  },
  {
    name: "Urad",
    season: "Kharif",
    type: "Pulses",
    icon: <GiBean className="text-black" />,
    description: "Black gram pulse crop",
    idealConditions: "Warm and humid, loamy soil",
  },
  {
    name: "Wheat",
    season: "Rabi",
    type: "Cereals",
    icon: <GiWheat className="text-brown-500" />,
    description: "Major winter cereal crop",
    idealConditions: "Cool weather, fertile loam",
  },
  {
    name: "Guar Seed",
    season: "Kharif",
    type: "Fodder",
    icon: <GiGrass className="text-green-400" />,
    description: "Fodder crop also used for gum extraction",
    idealConditions: "Arid and semi-arid regions, sandy loam soil",
  },
];
export default cropData;
